'use client';

import { useState, useEffect } from 'react';
import { Copy, Check } from 'lucide-react';
import { codeToHtml } from 'shiki';

// ============================================================
// CodeBlock — syntax highlighted code with copy button
// Uses shiki for 50+ language support, dark theme always
// Line numbers for blocks > 5 lines
// ============================================================

interface CodeBlockProps {
  code: string;
  language?: string;
  showLineNumbers?: boolean;
}

export function CodeBlock({ code, language = 'text', showLineNumbers }: CodeBlockProps) {
  const [html, setHtml] = useState<string>('');
  const [copied, setCopied] = useState(false);

  const lines = code.split('\n').length;
  const displayLineNumbers = showLineNumbers ?? lines > 5;

  useEffect(() => {
    let cancelled = false;

    const highlight = async () => {
      try {
        const result = await codeToHtml(code, {
          lang: language,
          theme: 'github-dark',
        });
        if (!cancelled) setHtml(result);
      } catch {
        // Fallback to plain text if language not supported
        try {
          const result = await codeToHtml(code, { lang: 'text', theme: 'github-dark' });
          if (!cancelled) setHtml(result);
        } catch {
          if (!cancelled) setHtml(`<pre><code>${escapeHtml(code)}</code></pre>`);
        }
      }
    };

    highlight();
    return () => { cancelled = true; };
  }, [code, language]);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(code);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard not available
    }
  };

  return (
    <div className="group relative my-3 rounded-xl overflow-hidden border border-[#30363d] bg-[#0d1117]">
      {/* Header bar */}
      <div className="flex items-center justify-between px-4 py-2 bg-[#161b22] border-b border-[#30363d]">
        <span className="text-[11px] font-mono text-[#7d8590] uppercase tracking-wider">
          {language}
        </span>
        <button
          type="button"
          onClick={handleCopy}
          className="flex items-center gap-1.5 text-[11px] text-[#7d8590] hover:text-[#e6edf3] transition-colors"
          title="Copy code"
        >
          {copied ? (
            <>
              <Check size={13} className="text-emerald-400" />
              <span className="text-emerald-400">Copied</span>
            </>
          ) : (
            <>
              <Copy size={13} />
              <span>Copy</span>
            </>
          )}
        </button>
      </div>

      {/* Code content */}
      {html ? (
        <div
          className={`overflow-x-auto text-[13px] leading-relaxed ${displayLineNumbers ? 'code-with-line-numbers' : ''}`}
          // HTML is generated by shiki (safe — shiki escapes content)
          dangerouslySetInnerHTML={{ __html: html }}
        />
      ) : (
        <pre className="overflow-x-auto p-4 text-[13px] leading-relaxed text-[#e6edf3] font-mono">
          <code>{code}</code>
        </pre>
      )}
    </div>
  );
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
