'use client';

import { useState } from 'react';
import { X, ZoomIn } from 'lucide-react';

// ============================================================
// ImagePreview — shows generated image with lightbox expand
// ============================================================

interface ImagePreviewProps {
  imageUrl: string;
  label?: string;
}

export function ImagePreview({ imageUrl, label = 'Generated Image' }: ImagePreviewProps) {
  const [lightboxOpen, setLightboxOpen] = useState(false);

  return (
    <>
      <div className="my-3 inline-block">
        <div
          className="relative group cursor-zoom-in rounded-xl overflow-hidden border border-[var(--border)] max-w-[400px]"
          onClick={() => setLightboxOpen(true)}
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={imageUrl}
            alt={label}
            className="w-full h-auto object-cover"
            loading="lazy"
          />
          <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center">
            <ZoomIn className="w-8 h-8 text-white opacity-0 group-hover:opacity-100 transition-opacity drop-shadow-lg" />
          </div>
        </div>
        <p className="text-[11px] text-[var(--muted-foreground)] mt-1.5 flex items-center gap-1">
          <span className="text-blue-400">✦</span>
          Generated by Gemini Image
        </p>
      </div>

      {/* Lightbox */}
      {lightboxOpen && (
        <div
          className="fixed inset-0 z-50 bg-black/90 flex items-center justify-center p-4"
          onClick={() => setLightboxOpen(false)}
        >
          <button
            onClick={() => setLightboxOpen(false)}
            className="absolute top-4 right-4 p-2 rounded-full bg-white/10 hover:bg-white/20 text-white transition-colors"
          >
            <X size={20} />
          </button>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={imageUrl}
            alt={label}
            className="max-w-full max-h-full object-contain rounded-lg"
            onClick={(e) => e.stopPropagation()}
          />
        </div>
      )}
    </>
  );
}
