'use client';

import { memo, useState, useCallback } from 'react';
import { Copy, Check, RefreshCw, Trash2 } from 'lucide-react';
import { MODELS, type ModelId } from '@/lib/utils/constants';
import { MarkdownRenderer } from './MarkdownRenderer';
import type { Message } from '@/lib/supabase/types';

interface MessageBubbleProps {
  message: Message;
  onRegenerate?: (messageId: string) => void;
  onDelete?: (messageId: string) => void;
}

export const MessageBubble = memo(function MessageBubble({
  message,
  onRegenerate,
  onDelete,
}: MessageBubbleProps) {
  const [copied, setCopied] = useState(false);
  const [showActions, setShowActions] = useState(false);

  const model = MODELS[message.model as ModelId];
  const modelColor = model?.color ?? '#737373';

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(message.content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [message.content]);

  const relativeTime = useRelativeTime(message.created_at);

  // Check for generated image in attachments
  const attachments = (message.attachments || []) as Array<{
    type?: string;
    data?: string;
    name?: string;
    url?: string;
  }>;
  const generatedImage = attachments.find(
    (a) => a.type?.startsWith('image') && a.data
  );

  if (message.role === 'user') {
    return (
      <div
        className="flex justify-end group"
        onMouseEnter={() => setShowActions(true)}
        onMouseLeave={() => setShowActions(false)}
      >
        <div className="relative max-w-[80%]">
          {/* User actions */}
          {showActions && (
            <div className="absolute -left-20 top-1 flex items-center gap-1 animate-fade-in">
              <button
                onClick={handleCopy}
                className="p-1 rounded hover:bg-[var(--secondary)] transition-colors cursor-pointer"
                title="Copy"
              >
                {copied ? (
                  <Check className="w-3.5 h-3.5 text-[var(--success)]" />
                ) : (
                  <Copy className="w-3.5 h-3.5 text-[var(--muted-foreground)]" />
                )}
              </button>
              {onDelete && (
                <button
                  onClick={() => onDelete(message.id)}
                  className="p-1 rounded hover:bg-[var(--secondary)] transition-colors cursor-pointer"
                  title="Delete"
                >
                  <Trash2 className="w-3.5 h-3.5 text-[var(--muted-foreground)]" />
                </button>
              )}
            </div>
          )}
          <div className="rounded-2xl rounded-br-md px-4 py-3 text-sm bg-[var(--primary)] text-[var(--primary-foreground)] leading-relaxed">
            <div dir="auto">{message.content}</div>
            {/* Attached images */}
            {attachments
              .filter((a) => a.type?.startsWith('image') && a.url)
              .map((a, i) => (
                <img
                  key={i}
                  src={a.url}
                  alt={a.name || 'attachment'}
                  className="max-w-[300px] rounded-lg mt-2"
                  loading="lazy"
                />
              ))}
          </div>
          <div className="text-[10px] text-[var(--muted-foreground)] mt-1 text-right opacity-0 group-hover:opacity-100 transition-opacity">
            {relativeTime}
          </div>
        </div>
      </div>
    );
  }

  // Assistant message
  return (
    <div
      className="flex gap-3 group"
      onMouseEnter={() => setShowActions(true)}
      onMouseLeave={() => setShowActions(false)}
    >
      {/* Model avatar */}
      <div
        className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5 text-white text-[10px] font-bold"
        style={{ backgroundColor: modelColor }}
      >
        {(model?.shortName ?? 'AI').charAt(0)}
      </div>

      {/* Message content */}
      <div className="flex-1 min-w-0">
        <div className="text-sm text-[var(--foreground)] leading-relaxed">
          <MarkdownRenderer content={message.content} />

          {/* Generated image */}
          {generatedImage && (
            <div className="mt-3">
              <img
                src={`data:${generatedImage.type};base64,${generatedImage.data}`}
                alt={generatedImage.name || 'Generated image'}
                className="max-w-[400px] rounded-lg border border-[var(--border)]"
              />
              <p className="text-xs text-[var(--muted-foreground)] mt-1">
                Generated by Gemini Flash Image
              </p>
            </div>
          )}
        </div>

        {/* Actions bar */}
        <div
          className={`flex items-center gap-1 mt-1.5 transition-opacity ${
            showActions ? 'opacity-100' : 'opacity-0'
          }`}
        >
          <button
            onClick={handleCopy}
            className="p-1 rounded hover:bg-[var(--secondary)] transition-colors cursor-pointer"
            title="Copy"
          >
            {copied ? (
              <Check className="w-3.5 h-3.5 text-[var(--success)]" />
            ) : (
              <Copy className="w-3.5 h-3.5 text-[var(--muted-foreground)]" />
            )}
          </button>
          {onRegenerate && (
            <button
              onClick={() => onRegenerate(message.id)}
              className="p-1 rounded hover:bg-[var(--secondary)] transition-colors cursor-pointer"
              title="Regenerate"
            >
              <RefreshCw className="w-3.5 h-3.5 text-[var(--muted-foreground)]" />
            </button>
          )}
          {onDelete && (
            <button
              onClick={() => onDelete(message.id)}
              className="p-1 rounded hover:bg-[var(--secondary)] transition-colors cursor-pointer"
              title="Delete"
            >
              <Trash2 className="w-3.5 h-3.5 text-[var(--muted-foreground)]" />
            </button>
          )}
          <span className="text-[10px] text-[var(--muted-foreground)] ml-2">
            {model?.shortName ?? message.model} &middot; {relativeTime}
          </span>
        </div>
      </div>
    </div>
  );
});

function useRelativeTime(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const seconds = Math.floor(diff / 1000);
  if (seconds < 60) return 'just now';
  const minutes = Math.floor(seconds / 60);
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}
